trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- bash: |
    echo ">>> Typecheck"
    npm i && npm run typecheck
  displayName: Typecheck
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Publish"
    npm run deploy -- -p $(VSCODE_MARKETPLACE_TOKEN)
  displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
