name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
    branches:
        include: ["*"]
    tags:
        include: ["*"]
pr: none

resources:
    repositories:
        - repository: templates
          type: github
          name: microsoft/vscode-engineering
          ref: main
          endpoint: Monaco

extends:
    template: azure-pipelines/extension/stable.yml@templates
    parameters:
        ghCreateRelease: true
        ghReleaseAddChangeLog: true
        buildSteps:
            - script: npm install -ci
              displayName: Install dependencies
